Update with new type specs
Kajabi/sage-archived pull request #115
Opened 2020-03-24 20:35 UTC by philschanely

- [ ] Work in updated type specs

2020-03-25 20:25 UTC, teenwolfblitzer requested changes
One issue to look at before 👍, seems a couple of the recent switch changes didn't get pulled through completely.

2020-03-25 20:25 UTC, monkeypox8 commented on app/views/sage/examples/objects/nav/_preview.html.erb
>    <a hre="#" class="sage-nav__link">Nav Link</a>
looks like the `href` is missing the `f` here and below.

2020-03-25 20:25 UTC, monkeypox8 commented on app/assets/stylesheets/sage/system/tokens/_color_palette.scss
> +    100: #fff,
🏳️

2020-03-25 20:25 UTC, monkeypox8 commented on app/assets/stylesheets/sage/system/patterns/elements/_switch.scss
> +  input[type="checkbox"] {
Looks like this change reverted a recent update, using the class over the element selector (screen below of unstyled radio button)

![switch-radio](https://user-images.githubusercontent.com/816579/77581650-54358000-6e9b-11ea-984e-74695667da92.png)

2020-03-25 20:25 UTC, monkeypox8 commented on app/assets/stylesheets/sage/system/patterns/elements/_switch.scss
> +    // checked
Invalid/error state missing here

2020-03-25 20:25 UTC, monkeypox8 commented on app/assets/stylesheets/sage/system/patterns/elements/_form_input.scss
> +  @extend %t-sage-body-xsmall-semi;
🚀

2020-03-25 21:08 UTC, philschanely commented on app/assets/stylesheets/sage/system/patterns/elements/_switch.scss
> +  input[type="checkbox"] {
This must have been a merge mishap; I'd definitely have preferred the BEM name here...

2020-03-26 00:06 UTC, teenwolfblitzer approved these changes
👍 LGTM, nicely done!

2020-03-26 14:26 UTC, merged