Sage-Menu
Kajabi/sage-archived pull request #290
Opened 2020-06-22 20:03 UTC by AndrwM

## Description
Forks functionality and style from `sage-live-option-menu`
Adds some initial deprecation concepts to the sidebar navigation
Deprecate `sage-live-option-menu`

### Screenshots
tba

## Related
#287

-

2020-06-24 22:04 UTC, teenwolfblitzer requested changes
This is looking great, but I think we'll need to address the keyboard accessibility of the menu and button as noted below. It seems likely we'll have necessary functions embedded within the menus once rolled out to the app.

2020-06-24 22:04 UTC, teenwolfblitzer commented on app/views/examples/objects/dropdown/_markup.html.erb
> +<div class="sage-dropdown" role="dropdown" aria-label="Participant options">
I think we may need to alter the parent structure of this somewhat, as the menu inside of the button doesn't appear to be accessible via keyboard.

Usually, a button can be actuated using the space bar or enter key. But even if we used a `button` element here in place of the `.sage-btn` `div`, the embedded structure may seem confusing to a screenreader. We'd probably need to set/unset `tabindex` on the menu container as the button is expanded/contracted, for example. I'm also not sure if the button 'click' would also intercept keyboard navigation to a menu option.

I think what we'll end up needing is a container surrounding a button with the `.sage-dropdown` menu as a sibling. A good example of this can be seen here: https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html which is reaaally close to what you've got in place.

2020-06-24 22:04 UTC, teenwolfblitzer commented on lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
> +    z-index: (sage-z-index(modal) - 1);
`sage-z-index` can take incremental values, so you should be able to go with `sage-z-index(modal, -1)` here. I haven't tested with negative values, but it should work. Or actually, `sage-z-index(underlay)` might be even better

2020-06-24 22:04 UTC, teenwolfblitzer commented on lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
> +  &:focus {
Could we also add an `:active` state here? Once we have keyboard navigation functional it'll be a helpful indicator. Possibly the same style as `:focus` with a different border color?

2020-06-29 20:14 UTC, philschanely approved these changes
Very nice! Some small suggestions but 👍 otherwise.

2020-06-29 20:14 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
> +[aria-expanded="true"] ~ .sage-dropdown__container {
Can this be nested in `__container`?

2020-06-29 20:14 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
> +[aria-expanded="true"] ~ .sage-dropdown__container .sage-dropdown__menu {
Can this be nested in `__menu`?

2020-07-01 15:37 UTC, merged