WIP: Kajabi Admin Site Navigation: JS Init Listener, Sage Modal Refactor, Updates
Kajabi/sage-archived pull request #331
Opened 2020-07-13 14:58 UTC by AndrwM

- New JS Init Strategy
- Sage Panel: Adjustment to class names
- Sage Dropdown: Minor File Cleanup
- Sage Modal: Ability to request remote JS on Sage Trigger and cleanup click handlers after removal

2020-07-21 14:26 UTC, AndrwM commented on app/views/examples/objects/tabs/_markup.html.erb
> +</div>
Add Pane exampe

2020-07-21 14:53 UTC, AndrwM commented on lib/sage-frontend/javascript/system/tooltip.js
> +    positionTooltip(evt.target, tooltip, pos);
I did some cleanup here to clarify what datatype `e` represented.

2020-07-21 14:55 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_modal.scss
> +  margin: $-modal-padding-y $-modal-padding-x;
Using margin here to take advantage of margin collapsing.

2020-07-21 15:07 UTC, philschanely commented
@AndrwM reviewing now; consider running the linter as well. ❤️

2020-07-21 15:52 UTC, philschanely requested changes
Fabulous work on the JS! I looked with 🔍  at the new/updated CSS and markup so sorry in advance for all the nit-picking. 🤓 🙇‍♂️  

Excited about this work for sure!! 🙌

2020-07-21 15:52 UTC, philschanely commented on app/views/examples/objects/modal/_markup.html.erb
> +      <h1 class="t-sage-heading-5">Example Sage Modal</h1>
I'm seeing heading-4 as the type spec prescribed in the design.

2020-07-21 15:52 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_modal.scss
>    border-radius: sage-border(radius-large);
I think the design is asking for `radius` (`4px`) now.

2020-07-21 15:52 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_modal.scss
>    box-shadow: sage-shadow(lg);
Looks like the design is using `2xl` shadow now.

2020-07-21 15:52 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +  height: rem(60);
According to latest type spec, the line-height of the element should be 28px with top/bottom padding of 16px. Would you be open to switching to this padding rather than fixing the height? This plus your consideration of line clamping may be more flexible moving forward.

2020-07-21 15:52 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +    background-color: sage-color(grey, 200);
I don't see this BG color in the design spec; are they on board with this interpretation over the spec?

![Screen Shot 2020-07-21 at 11 30 21 AM](https://user-images.githubusercontent.com/17955295/88074556-915a0800-cb45-11ea-9c85-0f90d3e9e346.png)

2020-07-21 15:52 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +  &:before {
I'm getting some responsive squishing on these radios. :-/

![Screen Shot 2020-07-21 at 11 31 10 AM](https://user-images.githubusercontent.com/17955295/88074789-df6f0b80-cb45-11ea-9403-6c0f32583a1d.png)

2020-07-21 15:52 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +  color: $sage-tabs-default-color;
I'm seeing `charcoal, 400` for all states of this text color. Might be worth double-checking with Design how much they want tab styles aligned here.

2020-07-21 15:52 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +.sage-tabs:not(.sage-tabs--style-radio) .sage-tabs__tab {
Perhaps we can add a selector for `.sage-tabs__tab` and nest this as well as line 48 under it. It also seems that `.sage-tabs` is not needed before the `:not()` or the `.sage-tabs--style-radio`.

Thanks for this thought to guard the styles and thus avoid too many overrides! 🙌

2020-07-21 15:52 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +.sage-tabs:not(.sage-tabs--style-radio) .sage-tabs__tab--active {
Similar to above, this could be nested inside `.sage-tabs__tab--active` along with line 100 and the `.sage-tabs` is not needed at the front.

2020-07-21 15:52 UTC, philschanely commented on app/views/examples/objects/tabs/_markup.html.erb
> +    <button type="button" data-js-tabs-target="<%= option[:id] %>" class="sage-tabs__tab"><%= option[:text] %></button>
Focus styles differ between hyperlink and buttons here. Might be worth tidying up.

2020-07-21 15:52 UTC, philschanely commented on app/views/examples/objects/panel/_markup.html.erb
> +<section class="sage-panel">
Is there a design spec for this object?

2020-07-21 15:59 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +.sage-tabs:not(.sage-tabs--style-radio) .sage-tabs__tab {
Great idea! Thank you

2020-07-21 15:59 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +  &:before {
Ooops, fixing!

2020-07-21 16:00 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +    background-color: sage-color(grey, 200);
I'll double check on this one

2020-07-21 16:02 UTC, AndrwM commented on app/views/examples/objects/panel/_markup.html.erb
> +<section class="sage-panel">
I've been working off this for the spec: https://www.figma.com/file/XqyDa4KJg8qKy62HULoNyA/Navigation?node-id=169%3A142

This is a screengrab of Kajabi-Products:
![image](https://user-images.githubusercontent.com/565743/88078123-10e9d600-cb4a-11ea-87b3-ad0b9f8f491b.png)

2020-07-21 16:04 UTC, AndrwM commented on app/views/examples/objects/panel/_markup.html.erb
> +<section class="sage-panel">
This spacing is a little unconventional to take into account the type of content that goes into the containers.
- footer has less x-padding to allow for the button text to align with the title
- header-aside does the same but on the y-axis

2020-07-21 16:12 UTC, philschanely commented on app/views/examples/objects/panel/_markup.html.erb
> +<section class="sage-panel">
I see your point. I wonder though whether Design considered the hover and focus effects and how they would impact this spacing. 

It might be worth some fancier styling to set up cleaner padding by default but then to perhaps just offset the particular buttons to space as desired? This way perhaps the component is more content-ready for different possibilities while also accounting for this particular implementation?

2020-07-21 16:19 UTC, AndrwM commented on app/views/examples/objects/panel/_markup.html.erb
> +<section class="sage-panel">
I love that idea. I'll experiment with a button helper to account for this.

I brought this up with @croswell a few weeks back and let him know that the spacing was irregular but that I would see what I could do.

Since this isn't an official pattern in the spec it might be worth a chat with several of the Sage Design stakeholders to ask for more example comps of Admin using the Panel so that we can figure out a standard approach to padding.

2020-07-21 19:57 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +    background-color: sage-color(grey, 200);
I went ahead and reduced it, it was a bit heavy

2020-07-21 23:47 UTC, teenwolfblitzer approved these changes
👍  🔥  LGTM, some really great work! A few items to look through and a question for the group; nothing I can see that would block a merge.

2020-07-21 23:47 UTC, teenwolfblitzer commented on app/views/examples/objects/modal/_markup.html.erb
> +<dialog class="sage-modal" data-js-modal="cool-modal" role="dialog" aria-modal="true">
Interesting! I had thought `dialog` support was still not fully rolled out in Safari, but it appears to be working just fine. I would assume that we'd no longer need `role="dialog"` though, since the element itself has that role.

2020-07-21 23:47 UTC, monkeypox8 commented on app/views/examples/objects/modal/_markup.html.erb
> +      <a href="#" class="sage-btn sage-btn--tertiary" data-js-modal-close>Close Modal</a>
Hmm, I'm thinking both of these should be `button` elements just for the sake of this example.

2020-07-21 23:47 UTC, monkeypox8 commented on app/views/examples/objects/tabs/_markup.html.erb
> +<div class="sage-tabs sage-tabs--style-radio" data-js-tabs>
This is looking great! As a follow-up (not a blocker for this PR), I think we'll want to add in `id`s and `aria-controls` to tie the tabs + panels together, similar to [the recommended implementation](https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html)

2020-07-21 23:47 UTC, monkeypox8 commented on lib/sage-frontend/javascript/system/init.js
> +  initDocumentPresenceListener('[data-js-modal]',           Sage.modal.init,            false);
😎

2020-07-21 23:47 UTC, monkeypox8 commented on lib/sage-frontend/javascript/system/modal.js
> +  function init(el) {
Question for the group @philschanely @pixelflips , since this reminds me of a comment that Phil brought up on one of my PRs (and also because of Andrew's [comment below](https://github.com/Kajabi/sage/pull/331/files#r458160291)). I like that @AndrwM has already started the convention of setting module vars in all caps for example, and wonder if we can move forward with unifying naming conventions on JS variables functions, and arguments. `el` or `ele`/`elem` and `e` vs `evt` or `event`, etc. Standardizing our naming conventions here seems like a natural step since we're doing the same with CSS and BEM.

2020-07-21 23:47 UTC, monkeypox8 commented on lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
>    &:active {
Can this be combined with the `focus` styles above? the `border-bottom-color` could then be split out as a separate piece if necessary.

2020-07-21 23:47 UTC, monkeypox8 commented on lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
>    margin: 0 0 0 auto;
I think we can reduce this one down to just `margin-left: auto` so we won't have to override later

2020-07-21 23:47 UTC, monkeypox8 commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +  :not(.sage-tabs--style-radio) > & {
I suspect we may want to refactor this block in the near future since it feels a little too difficult to parse to me and the nesting gets pretty deep 🔦

2020-07-22 00:32 UTC, philschanely commented on lib/sage-frontend/javascript/system/modal.js
> +  function init(el) {
Perhaps add a list of our conventional names somewhere in our READEM or docs?

2020-07-22 00:42 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +  :not(.sage-tabs--style-radio) > & {
I see your point @monkeypox8; @AndrwM already reduced the complexity here a bit and I do appreciate the :not() that guards some of the default styling from having to be overridden later. On the other hand its visually different enough it may warrant a different object altogether. What do you think?

2020-07-22 00:43 UTC, philschanely approved these changes
Thanks for working through all the critique. 🙇‍♂️  🏆

2020-07-22 14:49 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +  :not(.sage-tabs--style-radio) > & {
@monkeypox8 @philschanely –
I've been struggling with whether to split it off into its own object. The idea that I keep coming back to is that the functionality and implementation in Products is the same.

They both:
- Use the same JS
- The same `.sage-tabs-pane` class
- Are implemented in Products as:
   ```
    <%= sage_component SageTabs, { style: "radio", items: ... } %>

    <%= sage_component SageTabsPane, { id: ... } do %> (block) <% end %>
   ```

I agree that the tabs scss is pretty hard to parse, I wonder if there is a clever abstraction we can use here. (Individual files for each Tab style? – I'm not sure).

2020-07-22 14:54 UTC, AndrwM commented on lib/sage-frontend/javascript/system/modal.js
> +  function init(el) {
I'll add this and ping you all for review. 👍

2020-07-22 15:08 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_dropdown.scss
>    &:active {
Good idea 👍 Updated

2020-07-22 15:13 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +  :not(.sage-tabs--style-radio) > & {
I refactored this to use pseudo selector variable names for better readability.

2020-07-23 15:18 UTC, merged