Copy button
Kajabi/sage-archived pull request #349
Opened 2020-07-23 16:58 UTC by philschanely

## Description
Adds a `data-js-copy-button` attr that can be added to a button in order to copy text to the clipboard (see Sandbox page now; will remove before merging).

2020-07-23 20:04 UTC, AndrwM requested changes
This looks great! Made some comments on the JS init. Lemme know if you wanna chat IRL about it!

2020-07-23 20:04 UTC, AndrwM commented on app/views/pages/sandbox.html.erb
> +</button>
Don't forget to remove :)

2020-07-23 20:04 UTC, AndrwM commented on lib/sage-frontend/javascript/system/copy-button.js
> +  }
If you're using the "Presence" init strategy, an argument is passed to the `init` that is an reference to the element in the DOM. In this current state, if there were 4 instances on the page this will be run 4 times (and therefore be bound 16 times 😉 ). 

When you refactor this would you mind unbinding to? I'd love for us to get into the habit of doing it (even though the performance overhead for this is in particular pretty minute).

See `Sage.dropdown.init` and `Sage.dropdown.unbind` as examples.

2020-07-23 20:06 UTC, teenwolfblitzer approved these changes
👍  Works great! Seems like it'd be pretty easy to also extend this functionality as a util for textareas, etc down the road as well 😎

2020-07-23 20:08 UTC, monkeypox8 commented on lib/sage-frontend/javascript/system/copy-button.js
> +  }
@AndrwM Is the mutationsobserver listener only for unbinding event listeners on the document?

2020-07-23 20:09 UTC, AndrwM commented on lib/sage-frontend/javascript/system/copy-button.js
> +  }
@monkeypox8 it's also for binding.

When a DOM element arrives that has the correct data-attr then it will be passed to `init` to be setup up. Then when it is removed from the DOM the instance will be passed to `unbind`.

2020-07-23 20:12 UTC, AndrwM commented on lib/sage-frontend/javascript/system/copy-button.js
> +  }
@monkeypox8 Here are the docs: https://github.com/uzairfarooq/arrive

😄

2020-07-23 20:17 UTC, monkeypox8 commented on lib/sage-frontend/javascript/system/copy-button.js
> +  }
Whoops, my wording there was unclear. I'd intended to ask was whether arrive's removing an element would also require manually unbinding its event listeners but that seems to be covered by the linked docs (and is likely good general practice anyway)

2020-07-24 01:32 UTC, philschanely commented on app/views/pages/sandbox.html.erb
> +</button>
Will do; left it in for testers' benefit. Pulled now.

2020-07-24 01:33 UTC, philschanely commented
> This looks great! Made some comments on the JS init. Lemme know if you wanna chat IRL about it!

Thanks, @AndrwM ! Does this look as you'd expect now?

2020-07-24 14:57 UTC, AndrwM approved these changes
Awesome, thanks for making these changes! +1

2020-07-24 14:57 UTC, AndrwM commented on lib/sage-frontend/javascript/system/copy-button.js
> +  function handleClick(ev) {
Can we move this into the "Functions" section?

2020-07-24 15:07 UTC, merged