Sage RadioList - WIP
Kajabi/sage-archived pull request #369
Opened 2020-08-06 17:56 UTC by joedakroub

## Description
We have need for a new object that contains a list of radio button options that can appear in a horizontal or vertical layout along with a corresponding pane that displays the content related to the chosen option.

The radio button option must contain a **Body** text token and an optional **Small Body** text token to describe the option. See https://sage-design-system.kajabi.com/pages/style/typography for more details.

### Example
<img width="554" alt="SageRadioList" src="https://user-images.githubusercontent.com/7331038/89565068-f7a08500-d7eb-11ea-85c2-78ccc0352739.png">

Currently, the [Sage Tab](https://sage-design-system.kajabi.com/pages/object/tabs) object contains an option for displaying radio buttons. However, we have decided to break this functionality out into its own object to keep things small and modular.

### Screenshots

|  before  |  after  |
|--------|--------|
|||

## Test notes

### Steps for testing
1. 

## Related

-

2020-08-07 21:00 UTC, philschanely approved these changes
Small fix suggested below for convention but 🏆  otherwise! 🙇‍♂️

2020-08-07 21:00 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +  &--layout-default {
We prefer this to be a separate declaration rather than using `&` here.

2020-08-07 21:00 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +  &--layout-stacked {
Same here.

2020-08-07 21:03 UTC, joedakroub commented on lib/sage-frontend/stylesheets/system/patterns/objects/_tabs.scss
> +  &--layout-default {
Good catch! Resolved.

2020-08-10 14:23 UTC, AndrwM requested changes
Really awesome stuff. I like that we're separating the `tab` and `choice` into their own elements. However I'm concerned about a few BEM leaks happening and think that we could rename `sage-tabs` to something a bit more descriptive of its use.

2020-08-10 14:23 UTC, AndrwM commented on app/views/examples/objects/tabs/_markup.html.erb
> +    <div class="sage-tabs__pane" id="<%= "#{id}-#{option[:id]}" %>" data-js-tabs-pane="<%= "#{id}-#{option[:id]}" %>" role="tabpanel"><%= option[:content] || "" %></div>
With this naming schematic `sage-tabs__pane` should be a child node of `sage-tabs` to follow BEM syntax structure

2020-08-10 14:23 UTC, AndrwM commented on app/views/examples/objects/tabs/_markup.html.erb
> +  </div>
I love the idea of having individual elements for a `tab` or a `choice` and extrapolating the interactivity into a parent object. This is NICE.

**2 Notes Here:**
- What does everyone think about renaming `sage-tabs` to something a bit more universal? On initial review it was confusing to me that this object to could accept `choice` and `tab` as children. Possibly:
```
sage-pane-controller
  sage-pane-controller__option
    sage-choice/tab
    sage-choice/tab
  sage-pane-controller__pane#name-of-pane1
  sage-pane-controller__pane#name-of-pane2
```
- Design has different bottom-margin requirement for "Tabs" (spacing `lg`) and "Choice" (spacing `md`). We should add some additional margin bottom to these `sage-tabs` (spacing `sm`, I think should suffice) to account for that additional spacing.

2020-08-10 14:23 UTC, AndrwM commented on lib/sage-frontend/javascript/system/tabs.js
> +
😍 👏

2020-08-10 14:23 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/elements/_choice.scss
> +  }
`sage-tab--active` seems like a leak to me. What's our strategy for child elements being affected by parent objects?

Since this is all handled by a single JS script (currently named `sage-tabs`). Why don't we have that script detect whether the element that it is affecting is a `sage-tab` or `sage-choice` and apply the appropriate active class? ----> `sage-tab--active`/`sage-choice--active`

2020-08-10 14:23 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/elements/_choice.scss
> +}
Same concern as above regarding BEM leaks. I'm not sure the best way to work around this without adding a modifier class to each choice.

2020-08-10 14:23 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/elements/_choice.scss
> +}
How about using a CSS grid for the tabs object?

The `grid-gap` property may give us what we need.

2020-08-10 14:23 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/elements/_tab.scss
> +/* stylelint-enable max-nesting-depth */
I don't think we need to disable the nesting-depth lint here.

2020-08-10 14:23 UTC, AndrwM commented on app/views/examples/objects/tabs/_props.html.erb
> +  <td>null</td>
This style modifier doesn't exist anymore. Please remove :)

2020-08-10 15:16 UTC, joedakroub commented on lib/sage-frontend/javascript/system/tabs.js
> +
It was a quick win since the JS code was so easy to work with!

2020-08-10 15:37 UTC, joedakroub commented on app/views/examples/objects/tabs/_markup.html.erb
> +  </div>
These are really good points @AndrwM. I struggled with this too and did have some thought about possibly renaming `sage-tabs` to something more generic. I could also see renaming `tab` and `choice` to something more specific, like `defaultTab` and `choiceTab` to better convey that they are tab elements and go inside a tab object.

Something like `sage-pane-controller` does get us into a more generic naming. Interesting article here with good guidelines about approaching the `tablist` from an ARIA perspective. That could be a possible name as well.

I'll get those spacing issue worked out; thank you!

2020-08-10 15:52 UTC, joedakroub commented on lib/sage-frontend/stylesheets/system/patterns/elements/_choice.scss
> +  }
This is a good thought about detecting the tab type and adjusting the active class. I can address that issue.

2020-08-11 14:19 UTC, joedakroub commented on lib/sage-frontend/stylesheets/system/patterns/elements/_choice.scss
> +  }
To address these issues, I added `data-sage-active-class` to the tab and choice elements. The JS script now uses this attribute to determine which active class to use. I made modifiers within each stylesheet to address the BEM leaks.

2020-08-11 14:20 UTC, joedakroub commented on app/views/examples/objects/tabs/_props.html.erb
> +  <td>null</td>
The style modifier exists to determine which element type to render, `tab` or `choice`

2020-08-11 14:35 UTC, joedakroub commented on app/views/examples/objects/tabs/_markup.html.erb
> +  </div>
I worked out the spacing issues between tab and choice.

2020-08-11 14:36 UTC, joedakroub commented on lib/sage-frontend/stylesheets/system/patterns/elements/_choice.scss
> +}
I moved the layout classes into tabs.scss and used a selector to target the child elements to adjust the spacing we need. The removes the BEM leak and puts the control back into the tabs object.

2020-08-11 15:36 UTC, philschanely commented on app/views/examples/objects/tabs/_markup.html.erb
> +  </div>
Validated the spacing change.

2020-08-11 15:37 UTC, philschanely commented
In Andrew's absence I'm vouching this is good to merge. We can revisit any potential renaming later as needed.

2020-08-11 15:39 UTC, merged