[WIP] Update page heading to include additional items
Kajabi/sage-archived pull request #413
Opened 2020-09-15 20:29 UTC by pixelflips

## Description
Updates page headings to include action links, secondary text, and a help paragraph.

### Screenshots

|  Before  |  After  |
|--------|--------|
|![Screen Shot 2020-09-15 at 1 25 16 PM](https://user-images.githubusercontent.com/1175111/93261025-0a956600-f757-11ea-8eba-289a8ba63901.png)|![page-title-updates](https://user-images.githubusercontent.com/1175111/93261218-46303000-f757-11ea-8559-bab88f426479.png)|

## Related
- NA

2020-09-15 20:31 UTC, pixelflips commented
@AndrwM this is the initial draft for the page heading updates. Feel free to pull it down and adjust however you see fit and also add the additional variation we discussed.

2020-09-21 20:51 UTC, philschanely requested changes

2020-09-21 20:51 UTC, philschanely commented on app/views/examples/objects/page_heading/_preview.html.erb
> +  title_copy: "",
Could we do something to make these props not required and thus trim down the space in our preview file? Not sure how to do this with the components but before I would do something like `if defined?(prop)` in the template file. I imagine you know more about this than I do though ;)

2020-09-21 20:51 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +    "crumbs crumbs"
FYI if there's a chance you don't want `crumbs` to spill into the space above the `actions` you can use `crumbs . ` to make an empty cell.

2020-09-21 20:51 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  .sage-page-heading__toolbar--icon-#{$-icon-name} {
May be that we'll solve this differently in light of our button discussion. But did you find that this loop slowed down the compiling? I am a little concerned that we not have too many loops like this where we go through our entire icon library. May be that we should start consolidating such things into one place and thus only do the loop once. Just thinking out loud.

2020-09-21 20:51 UTC, philschanely commented on lib/sage_rails/app/views/sage_components/_sage_page_heading.html.erb
> +  <div class="sage-page-heading__title">
Should the title be first in the source order? I love that Grid gives us the full flexibility to think more about what source order makes the most sense to screen readers. Perhaps there's more to reorder as a result?

2020-09-21 20:51 UTC, philschanely commented on lib/sage_rails/app/views/sage_components/_sage_page_heading.html.erb
> +      <p class="sage-page-heading__title--help"><%= component.title_copy %></p>
This should not be a modifier; should it perhaps be `.sage-page-heading__lead`, or `__copy` or `__intro`?

2020-09-21 20:51 UTC, philschanely commented on lib/sage_rails/app/views/sage_components/_sage_page_heading.html.erb
> +      <a href="<%= item[:url] %>" class="<%= "sage-page-heading__toolbar--icon-#{item[:icon]}" if defined?(item[:icon]) %>"><%= item[:text] %></a>
This is also an incorrect application of a modifier. Consider instead `sage-page-heading__toolbar-icon-...`. 

In case its helpful reminder to clarify:

- a modifier should be a style modification to another element or block.
- modifiers are always stacked with the original block or element name. So if a `page-heading` block had a "super" modifier, it would be `page-heading--super` and you'd provide it with `page-heading page-heading--super`. Or if a Page Heading's Title element had a "warning" modifier it would be `page-heading__title--warning` and you'd provide it with `page-heading__title page-heading__title--warning`

You seem to be using it here and in the place above as an additional nested element. Such cases can just be treated just as elements themselves, named to fit whatever the thing semantically is in context. 

Hope this is helpful.

2020-09-21 20:51 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +    grid-template-columns: span 2;
Should probably just do one column here.

2020-09-21 20:51 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +@media (max-width: sage-breakpoint()) {
Let's prefer nesting media queries inside the affected selector rather than grouping them together. This way you can see right inside the selector all the styles that affect it.

2020-09-21 20:51 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  display: grid;
If these are not in effect for certain viewports lets guard them with a `min-width` filter. This makes what's happening at each viewport clearer versus what is not affected by viewport.

2020-09-21 20:51 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  grid-template-columns: 1fr max-content;
`1fr auto` may suffice here. Or you might consider a ratio-based `minmax()` to help ensure that a wider right side does not dominate and squash the left side.

2020-09-21 20:51 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  display: flex;
You could probably add `gap: sage-spacing(sm)` here to achieve the desired space between buttons.

2020-09-21 20:51 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  grid-template-areas:
I think you can now add `grid-gap: sage-spacing(sm)` to enforce the desired spacing and remove margins on the elements themselves. Another beautiful grid feature! 🙌

2020-09-21 20:51 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  margin-top: sage-spacing(sm);
Depending on what this is supposed to be, it may be more effective to use a grid cell alignment run on the `title` element.

2020-09-21 20:51 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  font-size: rem(14);
Can we extend a type spec here instead of setting a font size? This appears to be the first time I've seen `italic` used in our app! Consider whether this even deserves a new type spec added.

2020-09-21 20:51 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  margin-top: sage-spacing(sm);
Looking closer I think this should be on its own row in the grid. Beauty of the grid is that if this is not present then the row flattens to 0. Consider that being:
```
...
intro .
...
```

2020-09-21 21:12 UTC, AndrwM requested changes
Love how this is coming along! Left a few comments

2020-09-21 21:12 UTC, AndrwM commented on app/views/examples/objects/page_heading/_preview.html.erb
> +  title_copy: "",
What is the usage difference between `title_copy` and `title`?

2020-09-21 21:12 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  }
Color and spacing should be a concern of the child components here. We should probably remove this to prevent unexpected cascade behavior.

2020-09-21 21:12 UTC, AndrwM commented on lib/sage_rails/app/views/sage_components/_sage_page_heading.html.erb
> +<section class="sage-page-heading sage-spacer-bottom-sm">
If we're including a spacer by default within a component it should be within the `sage-page-heading` scss file rather than being defined as a class.

However if you want to add bottom margin in some instances but not all instances add ```<%= generated_css_classes %>``` to this node will allow devs to change the spacer when needed.

This is what the implementation could look like on the Products side:
```
<%= sage_component SagePageHeading, {
  title: "Page Title",
  spacer: { bottom: :sm },
....
```

Implementation source:
https://github.com/Kajabi/sage/blob/46af05bcb0bbcd27c61ed9dbbe2509b15c3c7520/lib/sage_rails/app/sage_components/sage_component.rb#L17-L29

2020-09-21 21:14 UTC, AndrwM commented on app/views/examples/objects/page_heading/_preview.html.erb
> +  title_copy: "",
Ah, okay I see – I think it would be best here to use a `content_for` snippet where any Rails block could be passed in, ping me and I'll show you how this works!

2020-09-21 21:14 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  }
@AndrwM I agree on color, but not quite on spacing. Here we could use `gap` on `__toolbar` to enforce the spacing of these elements in this context and thus avoid specifying spacing directly on the elements.

2020-09-21 21:15 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  }
Great idea! 👍

2020-09-21 21:16 UTC, philschanely commented on lib/sage_rails/app/views/sage_components/_sage_page_heading.html.erb
> +<section class="sage-page-heading sage-spacer-bottom-sm">
Lets def include the spacer option on the component! 🙌 

Future grid and spacing setup should come from parent/context but having that spacer as an option on the component is a win!

2020-09-21 22:38 UTC, pixelflips commented on lib/sage_rails/app/views/sage_components/_sage_page_heading.html.erb
> +      <p class="sage-page-heading__title--help"><%= component.title_copy %></p>
> This should not be a modifier; should it perhaps be `.sage-page-heading__lead`, or `__copy` or `__intro`?

Updated to __intro based on our conversation. Thanks again!

2020-09-22 22:57 UTC, pixelflips commented on lib/sage_rails/app/views/sage_components/_sage_page_heading.html.erb
> +<section class="sage-page-heading sage-spacer-bottom-sm">
This is fantastic, will add.

2020-09-22 22:57 UTC, pixelflips commented on app/views/examples/objects/page_heading/_preview.html.erb
> +  title_copy: "",
@AndrwM thanks for the content_for intro. Definitely simplified and cleaned things up.

2020-09-22 22:58 UTC, pixelflips commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  font-size: rem(14);
@philschanely now extended. ❤️

2020-09-22 23:00 UTC, pixelflips commented on app/views/examples/objects/page_heading/_preview.html.erb
> +  title_copy: "",
@philschanely these we're greatly reduced and no longer required. @AndrwM had some thoughts and will reach out.

2020-09-23 15:56 UTC, philschanely reviewed
A few final suggestions here. Looking really good!

2020-09-23 15:56 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/elements/_breadcrumbs.scss
> +  margin-right: rem(8px);
Could we use `gap` on the container instead of `margin-right` here on the items?

2020-09-23 15:56 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
> +    margin: 0;
😎

2020-09-23 15:56 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  margin-top: sage-spacing(sm);
Can `grid-gap` be used on the container instead of these `margin-x` settings?

2020-09-23 15:56 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  align-items: flex-start;
Could these settings that change responsively be wrapped in a media query that boxes them to the space they're used? This may help make it more explicit what is changing responsively versus what is constant. 

In this case you might have this:
```
.sage-page-heading__actions {
  grid-area: actions;
  display: flex;
  gap: sage-spacing(sm);
  // Hopefully margin can be removed in favor of a grid-gap setting on the header itself
  // margin-top: sage-spacing(sm);

  @media (max-width: sage-breakpoint(sm-max)) {
    flex-wrap: wrap;
    justify-content: flex-start;
  }

  @media (min-width: sage-breakpoint()) {
    flex-wrap: nowrap;
    justify-content: flex-end;
  }
}
```

2020-09-23 15:56 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  @media (min-width: sage-breakpoint()) {
Per my comment below about using grid-gap for margins, you might choose to revise to this here:

```
.sage-page-heading {
  display: grid;
  margin-bottom: sage-spacing(sm);

  @media (max-width: sage-breakpoint(sm-max)) {
    grid-template-columns: auto;
  }

  @media (min-width: sage-breakpoint()) {
    grid-template-areas:
      "crumbs ."
      "title actions"
      "intro ."
      "toolbar secondary";
    grid-template-columns: 1fr auto;
  }
}
```

2020-09-23 16:01 UTC, pixelflips commented on lib/sage-frontend/stylesheets/system/patterns/elements/_breadcrumbs.scss
> +  margin-right: rem(8px);
@philschanely good call, will adjust.

2020-09-23 16:27 UTC, pixelflips commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  margin-top: sage-spacing(sm);
@philschanely quick question. I initially tried using the gap on the container, but this would add a gap to all the tracks which caused the spacing/gap to remain even if the area had no content. Is there a workaround you might know of?

2020-09-23 16:39 UTC, pixelflips commented on lib/sage-frontend/stylesheets/system/patterns/objects/_page_heading.scss
> +  @media (min-width: sage-breakpoint()) {
@philschanely spacing should now be handled in the component, I just forgot to remove the margin so thanks for pointing that out.

A question around the media queries. Currently, I don't have grid applied to smaller screens since the different sections stack up nicely without. Could you clarify as to why I might need to update that just so I better understand?

2020-09-23 19:08 UTC, philschanely approved these changes
Spot on, dude! :tada

2020-09-23 21:29 UTC, merged