[wip] SageCatalogCard spike
Kajabi/sage-archived pull request #416
Opened 2020-09-17 21:07 UTC by AndrwM

2020-09-17 21:34 UTC, philschanely requested changes
Stellar work with the grid stuff, @AndrwM 😍 ! Some changes suggested below. Happy to discuss as needed.

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  padding: sage-spacing(sm) sage-spacing(sm) sage-spacing(sm) sage-spacing(md);
Double-check this with Sam as he may desire for this to be consistently 16px inside card. Then consider nudging the options element itself into the gutter if needed?

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  display: grid;
🙌

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  grid-template-areas:
Would you mind guarding the responsive props with a `min-width` for the aspects that change above sage-breakpoint? IMO this makes the overrides/changes clearer and simpler to trace properties in the inspector.

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  grid-template-rows: repeat(2, ($_content-height / 2));
Any reason not to let these be auto or omit altogether?

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  grid-template-columns: minmax(100px, 1fr) 5fr min-content;
This is 👍  but I interpreted it as `auto 1fr auto`... will that suffice? Do we actually want the image to scale? If so consider instead defining an absolute upper boundary such as `minmax(100px, 200px) 1fr auto`. If not, consider just `120px 1fr auto` if that image does need a bounded size. Just trying to reduce any magic-ness and bind the possibilities if possible.

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +$_content-height: 100px;
is the `$_` something new we should know about? We've been using `$-`

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  .sage-catalog-card {
😍   responsive grid!!

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  img {
Consider instead:

```
width: 100%;
height: 100%;
object-fit: cover;
```

2020-09-17 21:34 UTC, philschanely commented on app/views/pages/sandbox.html.erb
> +        <div class="sage-catalog-card__meta">
Could this be a `p` or allow type safely inside?

2020-09-17 21:34 UTC, philschanely commented on app/views/pages/sandbox.html.erb
> +        <div class="sage-catalog-card__body">
Could this be a `p` or allow type safely inside?

2020-09-17 21:34 UTC, philschanely commented on app/views/pages/sandbox.html.erb
> +        <div class="sage-catalog-card__actions">
Do we want the actions here in the source order? I would think the screen reader would prefer the content itself first. I imagine the image could even be last in the source order. 🎉  Grid areas!!

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +$_image-height: 64px;
Is the `$_` something new we should use? We have `$-` elsewhere. And be sure any of your `px` values are wrapped in `rem()`

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +    grid-template-areas:
You could probably switch to two columns here and update the configs accordingly.

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +@media (max-width: sage-breakpoint(sm-min)) {
Lets nest this inside `.sage-catalog-card__body` and then you don't need to repeat the selector.

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +@media (max-width: sage-breakpoint(sm-min)) {
Lets nest this inside `.sage-catalog-card` and then you don't need to repeat the selector.

2020-09-17 21:34 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_panel.scss
> +  .sage-panel--content-flush > &,
Consider instead letting the contents use negative margin to such them into the gaps? Regardless, may need `overflow: hidden` for rounded corners to show.

2020-09-18 17:42 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +$_content-height: 100px;
Whoops, nope!

2020-09-21 14:52 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/elements/_info.scss
> +  margin: 0 sage-spacing(sm) 0 0;
Instead of this default margin, could we instead add it in the context of being inside a certain container? For example, you could here do `.sage-catalog-card__info & { margin-right: sage-spacing(sm); }`. Or perhaps consider:

```
.sage-info-group {
  display: inline-flex;
  gap: sage-spacing(sm);
}
```
You could also consider just putting this rule on `.sage-catalog-card__info` itself too and avoid the extra container as a result.

Bottom line: this is a great example of where we can resist the urge to put on default margin and instead use context to add it when needed.

2020-09-21 14:52 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/elements/_info.scss
> +      margin: 0 sage-spacing(xs) 0 0;
Is it necessary to specify all sides at `0` or would just `margin-right` only suffice?

2020-09-21 14:58 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  @media (min-width: sage-breakpoint()) {
🙌 And this should probably switch to `@media (min-width: sage-breakpoint(md-min)) { ...`

2020-09-21 20:20 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  img {
This is causing the image to expand the column, reverted back to using the center position absolute solution. In this situation its more important to show the images in a uniform size than to show the entirety of the image.

2020-09-21 20:20 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  @media (min-width: sage-breakpoint()) {
Just for clarity on which breakpoint its using? Right on, will do

2020-09-21 21:54 UTC, philschanely approved these changes
Few small suggestions below. Excellent work on this stuff.

2020-09-21 21:54 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/elements/_button.scss
> +  padding: 0 sage-spacing(sm);
May not be necessary to override left and right spacing here. Since this is a modifier it only needs to tap the settings that are changing.

2020-09-21 21:54 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  grid-row-gap: sage-spacing(2xs);
Design specs seem to me to show 8px gap rather than 4px. Try that instead and then use `align-self: end` and `align-self: start` to `title` and `content` respectively. I wish there was a `pack-center` option but this may have to do for now.

2020-09-21 21:54 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  img {
Hmm I see. 🤔  Pros and cons on both sides. Seems this is also possible with a `max-height` on `__image` and then flex to center the image in the space. I suppose it comes down to why one or the other and I don't have a good reason other than trying to avoid absolute positioning when possible. This is certainly a feasible use for abs pos though, and I think that's better than adding a height dependency unless you think that benefits the situation.

2020-09-22 03:23 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_catalog_card.scss
> +  img {
I'd prefer to not use `max-height` with this to allow for the image container (and image) to grow to allow multiple lines of `sage-catalog-card__content`.

Example, in a smaller viewport with a lot of items:
![image](https://user-images.githubusercontent.com/565743/93841308-28842e80-fc61-11ea-87cd-17cf83221fab.png)

I generally agree with you on absolute position though this approach seems to give us what we need. I'm down to pair on this, maybe I'm missing something here 😄

2020-09-22 13:58 UTC, merged