Update SageRails SagePagination component
Kajabi/sage-archived pull request #439
Opened 2020-10-06 21:39 UTC by alimi

# Description

In https://github.com/Kajabi/kajabi-products/pull/15773, we're changing the `pager` helper so it no longer requires nor accepts `pager_params`. It wasn't needed in most cases, and Kaminari deprecated the way `pager_params` was being used. Instead, `pager` will optionally accept `additional_params`.

This PR updates `SagePagination` so it also optionally accepts `addtional_params`. It'll match `pager`'s behavior in kajabi-products and clear up the Kaminari deprecation warning.`additional_params` defaults to an empty hash so it plays nicely with Kaminari.

`SagePagination` still exposes the ability to set `pager_params` via `#pager_params=`. When `#pager_params=` is called, `additional_params` will be set instead. This will make it easier to switch from `pager_params` to `additional_params` in kajabi-products because both the old and new API will be supported.

## Test notes

There shouldn't be any change in behavior in any pagination links.

## Related
- https://github.com/Kajabi/kajabi-products/pull/15773

2020-10-09 15:07 UTC, AndrwM requested changes
We would prefer to handle than maintain backward compatibility. Would you mind updating?

Overall, the UXD team is excited to see PRs from outside our team being made to this repo. Thanks for digging into this. ✋

2020-10-09 15:07 UTC, AndrwM commented on lib/sage_rails/app/sage_components/sage_pagination.rb
> +  end
Is this mapping `pager_params` to `additional_params`?

We would prefer to update Kajabi-Products' implementation on Sage version-bump rather than maintaining backward compatibility with the `pager_params`.

2020-10-09 15:59 UTC, philschanely commented on lib/sage_rails/app/sage_components/sage_pagination.rb
> +  end
Agreed, @AndrwM. In a case like this as a very kind effort from @alimi to make an improvement, would we let this go through as-is but make our own note to follow up with the correction and requisite fix on `products`? Otherwise its unclear to me who will take responsibility to patch on `products`. 🤔

2020-10-09 16:44 UTC, monkeypox8 commented on lib/sage_rails/app/sage_components/sage_pagination.rb
> +  end
If I'm understanding correctly, the process would be similar in either approach. Either way, we'd need to update the old `pager_params` references. The difference being how soon we'd want to have that done, since the current implementation may maintain compatibility, but also presents the opportunity for those unfamiliar with the change post-Sagification to keep reusing the same pattern.

2020-10-09 17:34 UTC, alimi commented on lib/sage_rails/app/sage_components/sage_pagination.rb
> +  end
> We would prefer to update Kajabi-Products' implementation on Sage version-bump rather than maintaining backward compatibility with the `pager_params`.

Ah, ok. I added the backwards compatibility so kajabi-products would continue working whenever Sage was upgraded. But if we're gonna update kajabi-products whenever Sage is upgraded, that isn't really a concern. I can remove it.

> Otherwise its unclear to me who will take responsibility to patch on `products`. 🤔

I guess this would fall on whoever does the next Sage upgrade in kajabi-products? I'm still learning things and I'm not sure how the upgrade process works.

Also, [`SagePagination` is lightly used](https://github.com/Kajabi/kajabi-products/search?q=SagePagination) so it shouldn't be to hard to update when the time comes.

2020-10-13 14:17 UTC, AndrwM approved these changes
@alimi +1 Thanks for updating this! I'll plan to include this in v1.15.1 (targeting EOW)

2020-10-16 14:11 UTC, jacobthemyth approved these changes

2020-10-16 16:57 UTC, merged