Added Sage Rails Popover
Kajabi/sage-archived pull request #500
Opened 2020-10-28 13:52 UTC by QuintonJason

## Description

-[x] - added Sage Rails component
- [ ] - hook in JS for state change and a11y
- [ ] - updated docs

### Screenshots

|  before  |  after  |
|--------|--------|
|||

## Test notes

### Steps for testing
1.

2020-10-28 20:32 UTC, QuintonJason commented
Be sure to add the overlay behind the popover.

2020-10-28 20:36 UTC, QuintonJason commented
Make customizable trigger and pass in as a block to the popover

2020-11-02 16:44 UTC, philschanely reviewed
Solid work here! Some suggestions below. Also there's something inconsistent about the tabs in many of the files here. Not sure what would cause that, but itd be great to adjust for consistency. 🙌

2020-11-02 16:44 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_popover.scss
> +.sage-popover--is-expanded .sage-popover__button:not([aria-expanded="true"]) {
Could this go inside the `sage-popover__button` rule like this:

```
.sage-popover--is-expanded &:not([aria-expanded="true"]) { ... }
```

This way the `__button` styles are grouped together.

2020-11-02 16:44 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_popover.scss
> +  min-width: rem(250px);
Could we please set these with variables above? May be that we change them in the future, so it'd be nice to collect them at the top.

2020-11-02 16:44 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_popover.scss
> +  padding: 16px;
Is this an accidental remnant given next line?

2020-11-02 16:44 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_popover.scss
> +  height: 100%;
What do you think about right: 0, bottom: 0 instead and thus our mixing `@include position-full()`?

2020-11-02 16:44 UTC, philschanely commented on lib/sage_rails/app/views/sage_components/_sage_popover.html.erb
> +			<div class="">
Is this container intentional and necessary?

2020-11-02 16:44 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_popover.scss
> +  // transform: translate3d(sage-spacing(md), sage-spacing(2xs), 0);
Consider `@include sage-grid-stack()` here to standardize gaps between title, body, and actions.

2020-11-02 16:44 UTC, philschanely commented on lib/sage-frontend/stylesheets/system/patterns/objects/_popover.scss
> +  font-size: sage-font-size(sm);
Consider `@include sage-grid-stack()` here to standardize as well in case there are multiple children provided so that spacing is standard and consistent. Also consider extending a type spec here unless the one in the `p` below is sufficient.

2020-11-02 19:02 UTC, AndrwM requested changes
This rules! Some of the indention is wonky in the diff. Made some comments about the css selector namespacing and JS.

Great work!

2020-11-02 19:02 UTC, AndrwM commented on lib/sage_rails/app/sage_components/sage_popover.rb
> +	attr_accessor :content_link_text
Indention issue here :) – should be a double space for these

2020-11-02 19:02 UTC, AndrwM commented on app/views/examples/objects/page_heading/_preview.html.erb
> +    content_link_text: "Learn More"
These would be more clearly named as `link_url` and `link_text` to indicate what type of content should be passed in here.

2020-11-02 19:02 UTC, AndrwM commented on lib/sage_rails/app/views/sage_components/_sage_popover.html.erb
> +				} %>
The link href and text aren't being passed used in the component. They should be passed into this button.

2020-11-02 19:02 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_popover.scss
> +}
Should this be `.sage-popover` instead? In the css or the markup we don't have `sage-popover` defined but there are children namespaced as if they do have a parent.

2020-11-02 19:02 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_popover.scss
> +  }
Bem namespace needed here.

2020-11-02 19:02 UTC, AndrwM commented on lib/sage-frontend/javascript/system/popover.js
> +
Indentation is really large for this file. The pattern we use in this repo is 2-space indentation.

2020-11-02 19:02 UTC, AndrwM commented on lib/sage-frontend/javascript/system/popover.js
> +			}
`sage-popover--is-expanded` should be on the parent node and not the `body` based on its namespacing.

I think we can probably get away with not adding `body` classes for this component, management of `body` classes are technical debt that we'd like to stay way from.

2020-11-02 19:02 UTC, AndrwM commented on lib/sage-frontend/javascript/system/popover.js
> +      el.removeEventListener('keydown', popoverKeydownHandler);
Missing an unbind for the overlay

2020-11-02 19:03 UTC, AndrwM commented on lib/sage-frontend/stylesheets/system/patterns/objects/_popover.scss
> +  }
Should this be `--is-expanded`?

2020-11-02 19:04 UTC, AndrwM commented on lib/sage-frontend/javascript/system/popover.js
> +			}
We don't use body classes for Dropdown or Modal, use those components as ref. Happy to pair and refactor this JS together 🙆‍♂️

2020-11-05 21:47 UTC, joedakroub approved these changes
This looks great! Another nice addition to Page headings. 👍 

Added one suggestion, but nothing blocking. Nice work Quinton!

2020-11-05 21:47 UTC, joedakroub commented on app/views/examples/objects/page_heading/_preview.html.erb
> +  help_link: {
I wonder if grouping all the help-related items together would  help streamline the property names a bit? Just a thought.

```
{
  title: "Page Title",
  space: { bottom: :xl },
  help: {
    title: "About This Cool Thing",
    html: "<p>This is a block of content.</p>"
    link: {
      ..
    }
  }
}
```

2020-11-05 23:48 UTC, AndrwM approved these changes
+1 Looks great!

2020-11-05 23:48 UTC, AndrwM commented on lib/sage-frontend/javascript/system/popover.js
> +
Indention here too. Your IDE must convert indention to tabs :p 

Our Sage repo uses 2-space indention.

2020-11-06 14:26 UTC, QuintonJason commented on app/views/examples/objects/page_heading/_preview.html.erb
> +  help_link: {
Thanks for pointing this out. I'll take care of this one in a followup. Additional work will most likely be needed after implementation.

2020-11-06 14:27 UTC, merged